### ISSUE TITLE
Automatic key naming for element_name is pulling from text content rather than layer name

### ISSUE THREAD

**Issue by Craigtut** [lokalise/lokalise-sketchplugin#2]
Setting selected seems like key name should be autogenerating from the layer name:

<img width="524" alt="Screen Shot 2021-04-07 at 5 13 54 PM" src="https://user-images.githubusercontent.com/6494296/113949983-1c0e9000-97c5-11eb-86ba-e4e6568150ac.png">

I noticed that the auto generated key is pulling from the content of the text layer rather than the layer element name:

<img width="1242" alt="Screen Shot 2021-04-07 at 5 13 40 PM" src="https://user-images.githubusercontent.com/6494296/113949940-fed9c180-97c4-11eb-8f3e-8fb6252004f3.png">

**Comment by andrewLab-lokalise** [comment]
@Craigtut the issue was addressed in v1.1.2. Should be resolved by now.
